style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Dirrk/terraform-docs
options:
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - feature
    #     - fix
    #     - bugfix
  commit_groups:
    # title_maps:
    #   feat: Features
    #   fix: Bug Fixes
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject

  notes:
    keywords:
      - BREAKING CHANGE
