name: Pre-Release
on:
  push:
    branches:
      - release/**
jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Should generate README.md for this REPO
      uses: ./
      with:
        entrypoint: "/generate-readme.sh"
        tf_docs_git_push: "true"

  draft:
    runs-on: ubuntu-latest
    needs: ['readme']
    steps:
    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
