name: Release Tasks
on:
  release:
    types: [published]
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: push up major version tag
      uses: ./
      with:
        entrypoint: "/release.sh"
