name: 'Terraform fmt'
on:
  pull_request:
    paths:
      - '**.tf'
jobs:
  fmt:
    name: 'Terraform fmt'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: fmt
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: examples
          tf_actions_version: '0.12.17'
          tf_actions_subcommand: 'fmt'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
